### PR TITLE
test: add tests for prompt-wars

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: https://github.com/aufacicenta/pulsemarkets/issues/148
Fixes: https://github.com/aufacicenta/pulsemarkets/issues/147
Fixes: https://github.com/aufacicenta/pulsemarkets/issues/165

Screenshot 2023-10-18 at 6 58 29 AM

### CODE REVIEW

**Comment by Udit-takkar** [comment]
@netpoe ready for review

**Review by netpoe — CHANGES_REQUESTED** [review]
Looking good!
Nice Rust skills 🤙 

Just some warnings when running `cargo test -- --nocapture`: 

```
cargo test -- --nocapture            
   Compiling promptwars v0.1.0 (./contracts/prompt-wars)
warning: variable does not need to be mutable
   --> src/tests.rs:770:13
    |
770 |         let mut outcome_id = alice();
    |             ----^^^^^^^^^^
    |             |
    |             help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: variable does not need to be mutable
   --> src/tests.rs:771:13
    |
771 |         let mut result = 0.3;
    |             ----^^^^^^
    |             |
    |             help: remove this `mut`

warning: `promptwars` (lib test) generated 2 warnings (run `cargo fix --lib -p promptwars --tests` to apply 2 suggestions)
```

Otherwise, 3 new tests pass succesfully:

```
test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

Please fix the warnings and share your NEAR address to send 300 USDT 👍

**Comment by Udit-takkar** [comment]
@netpoe this is ready to merge

**Review by netpoe — APPROVED** [review]

**Comment by netpoe** [comment]
> Done. Here is my Account ID
> 
> Screenshot 2023-10-18 at 11 06 14 PM
Screenshot 2023-10-20 at 12 14 36

Sent!

**Pull request merged**
